### ISSUE TITLE
检查出错，能不能更新一下？

### ISSUE THREAD

**Issue by lukemin** [openmynet/tvboxsp#2]
root@VM-24-4-ubuntu:/backup/tvboxsp/target/release# ./tvboxsp -i https://raw.liucn.cc/box/m.json
[2023-07-21T06:21:54Z INFO ] 开始下载: https://raw.liucn.cc/box/m.json
[2023-07-21T06:22:02Z INFO ] 文件下载完成!
[2023-07-21T06:22:02Z INFO ] 开始解析文件...
Error: missing field `group` at line 5 column 175
root@VM-24-4-ubuntu:/backup/tvboxsp/target/release#

**Comment by openmynet** [comment]
后面会重构新的版本，支持ui操作界面，不在需要通过命令行操作

**Comment by lukemin** [comment]
> 后面会重构新的版本，支持ui操作界面，不在需要通过命令行操作

点赞，终于要跟新了。

**Comment by openmynet** [comment]
> > 后面会重构新的版本，支持ui操作界面，不在需要通过命令行操作
> 
> 点赞，终于要跟新了。

UI版本已更新
