### ISSUE TITLE
几个意见，希望能采纳。

### ISSUE THREAD

**Issue by lukemin** [openmynet/tvboxsp#3]
1.检测的时候能不能增加一个进度条？能中止，而不是一直卡着转圈。
2.合并的时候，增加源之后把填写的地方变成空的，而不是保留最后一个。
3.合并的源能不能保存，每次都要重新添加，并且添加的时候能添加，直接添加多个连接。

**Comment by openmynet** [comment]
> 1.检测的时候能不能增加一个进度条？能中止，而不是一直卡着转圈。 2.合并的时候，增加源之后把填写的地方变成空的，而不是保留最后一个。 3.合并的源能不能保存，每次都要重新添加，并且添加的时候能添加，直接添加多个连接。

第1点后面会添加， 第2，3点不清楚你指的是哪里，直播源还是tvbox的源

**Comment by lukemin** [comment]
![1705457069068](https://github.com/openmynet/tvboxsp/assets/12003375/e8449e3d-46c6-466b-8f44-620f273b6a90)
1.添加的地方默认为空，而不是最后一个链接。
2.添加的时候可以一次添加多个，直接一个大的输入框，一行一个链接，而不是一个一个的添加。
3.添加之后可以保存，而不是关闭之后就恢复了。

**Comment by openmynet** [comment]
done
