### ISSUE TITLE
希望增加Windows版本

### ISSUE THREAD

**Issue by youniube** [openmynet/tvboxsp#4]
希望增加Windows版本，谢谢

**Comment by openmynet** [comment]
已经包含了windows版本，https://github.com/openmynet/tvboxsp/releases/tag/0.0.2 ， msi格式即为windows安装包， 如果你需要的是macos版本的话；由于我没有macos设备，所以macos版本需要你自己下载源代码进行打包， 打包教程：https://tauri.app/v1/guides/building/macos

**Comment by youniube** [comment]
好的，谢谢
